# Generated by Django 3.2.15 on 2022-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(default=False, max_length=500),
            preserve_default=False,
        ),
    ]
